application: calendar-poll
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(.+\..+)
  static_files: www/\1
  upload: www/.*

- url: /db/.*
  script: db.py

- url: /review/.{6}
  static_files: www/review.html
  upload: www/.*

- url: /review/.*
  script: db.py

- url: /.*
  static_files: www/index.html
  upload: www/.*